package com.example.meal_card_api;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/meal") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called mealRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MealRepository mealRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewMeal (@RequestParam String name
            , @RequestParam String url) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Meal n = new Meal();
        n.setName(name);
        n.setUrl(url);
        mealRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Meal> getAllMeals() {
        // This returns a JSON or XML with the users
        return mealRepository.findAll();
    }
}
